Added more validators common problems to the proper section
desmos-labs/docs pull request #12
Opened 2021-09-08 15:14 UTC by bragaz

Added some more validators common problems to the proper section

2021-09-08 18:30 UTC, kwunyeung requested changes

2021-09-08 18:30 UTC, kwunyeung commented on docs/04-validators/06-common-problems.md
> +4) Unsafe reset your node with `desmos unsafe-reset-all`;
@bragaz should ask validators to backup `~/.desmos/data/priv_validator_state.json` before executing `unsafe-reset-all` so that they can keep the validator voting state to avoid double sign. Also having a backup of the `~/.desmos/config/addrbook.json` would help them connect to peers faster after restart.

2021-09-09 06:56 UTC, bragaz commented on docs/04-validators/06-common-problems.md
> +4) Unsafe reset your node with `desmos unsafe-reset-all`;
@kwunyeung you're right!!

2021-09-09 09:52 UTC, RiccardoM commented on versioned_docs/version-mainnet/04-validators/06-common-problems.md
> +   #  --chain-id morpheus-1001 \
Looks like this file is for the mainnet, but the chain id is `morpheus-1001`. Is it wanted? The same applied through all this file

2021-09-09 10:14 UTC, bragaz commented on versioned_docs/version-mainnet/04-validators/06-common-problems.md
> +   #  --chain-id morpheus-1001 \
Definitely a mistake, thanks!

2021-09-09 14:11 UTC, RiccardoM commented on versioned_docs/version-mainnet/04-validators/06-common-problems.md
> +the [testnet repository](https://github.com/desmos-labs/morpheus). This happens because all nodes have a limit of
I think this should be pointing towards the mainnet repo?

2021-09-13 08:18 UTC, RiccardoM approved these changes

2021-09-13 08:19 UTC, merged